[tools]
go = "1"
node = "26"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
python = "3.14"

[bootstrap.packages]
"brew:tree" = "latest"
"brew:kubectx" = "latest"
"brew:fzf" = "latest"
"brew:starship" = "latest"
"brew:helm" = "latest"
"brew:bat" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"
